# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libudunits2-dev

after_success:
  - Rscript -e 'covr::codecov()'
